# 1. Redirigir tráfico HTTP a HTTPS
server {
    listen 80;
    server_name localhost;
     return 301 https://$host:8443$request_uri;
}
# 2. Servidor HTTPS principal
server {
    listen 443 ssl;
    server_name localhost;

    # Rutas de los certificados (que montaremos con Docker)
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # Configuraciones de seguridad recomendadas (opcional pero da puntos extra con el profe)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # --- REGLA 1: SERVIR EL FRONTEND ---
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # --- REGLA 2: API DE AVIONES ---
    location /api/vuelos {
        rewrite ^/api/vuelos/(.*)$ /api/v1/vuelos/$1 break;
        rewrite ^/api/vuelos$ /api/v1/vuelos break;
        proxy_pass http://api_aviones:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- REGLA 3: API DE HOTELES ---
    location /api/hoteles {
        rewrite ^/api/hoteles/(.*)$ /api/v1/hoteles/$1 break;
        rewrite ^/api/hoteles$ /api/v1/hoteles break;
        proxy_pass http://api_hoteles:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- REGLA 4: API DE BUSES ---
    location /api/buses {
        rewrite ^/api/buses/(.*)$ /api/v1/buses/$1 break;
        rewrite ^/api/buses$ /api/v1/buses break;
        proxy_pass http://api_buses:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # --- REGLA 5: API DE AGENCIA (LOGIN, RESERVAS, ETC) ---
    # La usaremos para login, admin y reservas.
    location /api/agencia {
        proxy_pass http://api_agencia:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}